handlers:
  - sink: ext://sys.stdout
    level: DEBUG
    format: "<green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green> | <level>{level}</level> | <cyan>{name}</cyan> | <magenta>{file}:{line}</magenta> | <yellow>{function}</yellow> | <cyan>{message}</cyan> | {extra}"
    enqueue: true
    colorize: true
# add more sink here if needed
extra:
  default: "mkit-version-1"
activation:
  - ["my_module.secret", false]
  - ["another_library.module", true]
